### ISSUE TITLE
AttributeError: 'StatusHandler' object has no attribute 'async_callback' in asynchronous_web_services/long_polling

### ISSUE THREAD

**Issue by zt706** [Introduction-to-Tornado/Introduction-to-Tornado#15]
self.application.shoppingCart.register(self.async_callback(self.on_message))
edit to:
self.application.shoppingCart.register(self.on_message)
because the new tornado don't need this function call

**Comment by bensooraj** [comment]
Yup, in fact starting Tornado v4.0 the `async_callback` functions have been removed. To quote the [Backwards-compatibility notes](http://www.tornadoweb.org/en/stable/releases/v4.0.0.html?highlight=async_callback#backwards-compatibility-notes):

> The RequestHandler.async_callback and WebSocketHandler.async_callback wrapper functions have been removed; they have been obsolete for a long time due to stack contexts (and more recently coroutines).

**Comment by mikedory** [comment]
Great, thanks for calling that out. We're no longer actively maintaining this repo (the book was written targeting Tornado 2.X), so it's likely some there are some issues like that.

**Comment by appleyuchi** [comment]
Then how to repair the code?

**Comment by bensooraj** [comment]
@appleyuchi I am quite not sure how I resolved it back then, but I had re-written (for Tornado 4.X) all the examples used in this book at [bensooraj/TornadoExamples](https://github.com/bensooraj/TornadoExamples). Check it out if it helps.

Honestly, I may not be of much help if something breaks there as well; it was a long time ago 😄 

Good luck learning!
