### ISSUE TITLE
The twitter API in chapter 5 is no longer valid

### ISSUE THREAD

**Issue by ozn0417** [Introduction-to-Tornado/Introduction-to-Tornado#17]
It looks like the twitter API in chapter 5 is no longer valid.  Requesting a new API.

**Comment by mikedory** [comment]
Hey @ozn0417 - we're not longer actively maintaining this repo (as the book is also no longer being updated), but we're happy to review and discuss revisions if you've got them. If you want to take a pass at a new API example, I'll be happy to chat more.

**Comment by greed2411** [comment]
the api has been changed by twitter, look at [this](https://developer.twitter.com/en/docs/tweets/search/api-reference/get-search-tweets) for doing it in 2018.

**Comment by greed2411** [comment]
Refer to the PR #20 or my fork of this repository over [here](https://github.com/greed2411/Introduction-to-Tornado)
